---
pushgateway_src_url: >-
  https://github.com/prometheus/pushgateway/releases/download/v1.3.1/pushgateway-1.3.1.linux-amd64.tar.gz
pushgateway_src_checksum: >-
  374055d60648961f4defe0f08c392f8bc0c9c17856a0e9ec34a063e35a6dec48
pushgateway_user: pushgateway
pushgateway_group: pushgateway
pushgateway_bin_path: /usr/local/bin
pushgateway_log_path: /var/log/pushgateway
pushgateway_log_file: pushgateway.log
pushgateway_web_listen_port: 9091
pushgateway_web_listen_address: "0.0.0.0:{{ pushgateway_web_listen_port }}"
pushgateway_cmdline_options: []
