---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: centos/8

suites:
  - name: prometheus1
    provisioner:
      command: |-
        sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" \
        /etc/ssh/sshd_config && sudo systemctl restart sshd
        if [ ! -b /dev/sdb1 ]; then
            sudo parted --script /dev/sdb mklabel gpt mkpart primary 0% 100%
        fi
    driver_config:
      vm_hostname: prometheus1.cluster.local
      network:
        - ["private_network", {ip: "192.168.1.14"}]
        - ["private_network", {ip: "192.168.3.210"}]
      customize:
        memory: 1024
        createhd:
          - filename: /tmp/drbd1.vdi
            size: 10240
        storagectl:
          - name: IDE
            portcount: 2
        storageattach:
          - storagectl: IDE
            port: 1
            device: 0
            type: hdd
            medium: /tmp/drbd1.vdi
  - name: prometheus2
    provisioner:
      command: |-
        sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" \
        /etc/ssh/sshd_config && sudo systemctl restart sshd
        if [ ! -b /dev/sdb1 ]; then
            sudo parted --script /dev/sdb mklabel gpt mkpart primary 0% 100%
        fi
    driver_config:
      vm_hostname: prometheus2.cluster.local
      network:
        - ["private_network", {ip: "192.168.2.14"}]
        - ["private_network", {ip: "192.168.3.211"}]
      customize:
        memory: 1024
        createhd:
          - filename: /tmp/drbd2.vdi
            size: 10240
        storagectl:
          - name: IDE
            portcount: 2
        storageattach:
          - storagectl: IDE
            port: 1
            device: 0
            type: hdd
            medium: /tmp/drbd2.vdi
  - name: haproxy1
    provisioner:
      command: |-
        sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" \
        /etc/ssh/sshd_config && sudo systemctl restart sshd
    driver_config:
      vm_hostname: haproxy1.cluster.local
      network:
        - ["private_network", {ip: "192.168.1.250"}]
        - ["private_network", {ip: "192.168.3.212"}]
  - name: haproxy2
    provisioner:
      command: |-
        sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" \
        /etc/ssh/sshd_config && sudo systemctl restart sshd
    driver_config:
      vm_hostname: haproxy2.cluster.local
      network:
        - ["private_network", {ip: "192.168.2.250"}]
        - ["private_network", {ip: "192.168.3.213"}]
  - name: ansible
    provisioner:
      name: ansible_playbook
      roles_path: .
      ansible_inventory: hosts
      playbook: playbooks/prometheus-cluster.yml
      ansible_playbook_command: >-
        ansible-playbook -e "ansible_user=vagrant 
        ansible_password=vagrant" --ssh-extra-args="-o ConnectTimeout=10 
        -o ConnectionAttempts=60 -o StrictHostKeyChecking=no" 
        -i /tmp/kitchen/hosts /tmp/kitchen/prometheus-cluster.yml
      require_chef_for_busser: false
      max_retries: 5
    driver_config:
      vm_hostname: ansible.cluster.local
      network:
        - ["private_network", {ip: "192.168.1.254"}]
