---
- name: install boto
  pip:
    name: boto

- name: request an acme certificate
  include_tasks: request_certificate.yml
  with_items: "{{ letsencrypt_certificates }}"
  loop_control:
    loop_var: certificate
