- set_fact:
    certificate_path: >-
      {{- letsencrypt_certs_path + '/' + certificate.common_name -}}

- name: create directory to store certs
  file:
    path: "{{ certificate_path }}"
    state: directory
    mode: 0700

- name: generate account key
  openssl_privatekey:
    path: "{{ certificate_path }}/account-key.pem"
    size: 4096

- name: generate signing key
  openssl_privatekey:
    path: "{{ certificate_path + '/' + certificate.common_name + '.pem' }}"
    size: 4096

- name: generate csr
  openssl_csr:
    common_name: "{{ certificate.common_name }}"
    subject_alt_name: "DNS:{{ certificate.subject_alt_name|join(',DNS:') }}"
    email_address: "{{ certificate.email_address|default(omit, true) }}"
    locality_name: "{{ certificate.locality_name|default(omit, true) }}"
    organization_name: >-
      {{- certificate.organization_name|default(omit, true) -}}
    organizational_unit_name: >-
      {{- certificate.organizational_unit_name|default(omit, true) -}}
    state_or_province_name: >-
      {{- certificate.state_or_province_name|default(omit, true) -}}
    country_name: "{{ certificate.country_name|default(omit, true) }}"
    privatekey_passphrase: >-
      {{- certificate.privatekey_passphrase|default(omit, true) -}}
    path: >-
      {{- certificate_path + '/' + certificate.common_name + '.csr' -}}
    privatekey_path: >-
      {{- certificate_path + '/' + certificate.common_name + '.pem' -}}

- name: create acme challenge
  acme_certificate:
    acme_version: 2
    terms_agreed: yes
    account_email: "{{ acme_email|default(omit, true) }}"
    account_key_src: "{{ certificate_path }}/account-key.pem"
    src: "{{ certificate_path + '/' + certificate.common_name + '.csr' }}"
    cert: "{{ certificate_path + '/' + certificate.common_name + '.crt' }}"
    challenge: dns-01
    acme_directory: >-
      {{- (letsencrypt_acme_environment == 'production')|
      ternary(letsencrypt_acme_production_directory, 
      letsencrypt_acme_staging_directory) -}}
    remaining_days: "{{ certificate.valid_days }}"
  register: challenge

- name: create route53 TXT record
  route53:
    zone: "{{ letsencrypt_route53_zone }}"
    record: "{{ challenge.challenge_data[item]['dns-01'].record }}"
    type: TXT
    ttl: 60
    value: '"{{ challenge.challenge_data[item]["dns-01"].resource_value }}"'
    overwrite: true
    state: present
    wait: yes
    aws_access_key: "{{ letsencrypt_aws_access_key|default(omit, true) }}"
    aws_secret_key: "{{ letsencrypt_aws_secret_key|default(omit, true) }}"
  with_items: "{{ [certificate.common_name] + certificate.subject_alt_name }}"
  when:
    - challenge is changed
    - letsencrypt_dns_provider == 'route53'

- name: validate acme challenge
  acme_certificate:
    acme_version: 2
    account_email: "{{ acme_email|default(omit, true) }}"
    account_key_src: "{{ certificate_path }}/account-key.pem"
    src: "{{ certificate_path + '/' + certificate.common_name + '.csr' }}"
    cert: "{{ certificate_path + '/' + certificate.common_name + '.crt' }}"
    challenge: dns-01
    acme_directory: >-
      {{- (letsencrypt_acme_environment == 'production')|
      ternary(letsencrypt_acme_production_directory, 
      letsencrypt_acme_staging_directory) -}}
    remaining_days: "{{ certificate.valid_days }}"
    fullchain: >-
      {{- certificate_path + '/' + certificate.common_name + 
      '-fullchain.crt' -}}
    chain: >-
      {{- certificate_path + '/' + certificate.common_name + 
      '-intermediate.crt' -}}
    data: "{{ challenge }}"
  when: challenge is changed

- name: delete route53 TXT record
  route53:
    zone: "{{ letsencrypt_route53_zone }}"
    record: "{{ challenge.challenge_data[item]['dns-01'].record }}"
    type: TXT
    ttl: 60
    value: '"{{ challenge.challenge_data[item]["dns-01"].resource_value }}"'
    overwrite: true
    state: absent
    aws_access_key: "{{ letsencrypt_aws_access_key|default(omit, true) }}"
    aws_secret_key: "{{ letsencrypt_aws_secret_key|default(omit, true) }}"
  with_items: "{{ [certificate.common_name] + certificate.subject_alt_name }}"
  when:
    - challenge is changed
    - letsencrypt_dns_provider == 'route53'

- name: download letsencrypt fakeroot certificate for staging environment
  get_url:
    url: https://letsencrypt.org/certs/fakelerootx1.pem
    dest: "{{ certificate_path }}/fakelerootx1.crt"
  when: letsencrypt_acme_environment == 'staging'
