- name: check if cluster can be upgraded
  shell: >-
    {{ kubernetes_install_path }}/kubeadm upgrade plan {{ upgrade_version }}
  register: upgrade_plan_result
  until: upgrade_plan_result.rc == 0
  retries: 10
  delay: 30
  changed_when: false

- name: drain control plane
  shell: >-
     KUBECONFIG={{ kubernetes_config_path }}/admin.conf
     {{ kubernetes_install_path }}/kubectl drain
     {{ hostvars[control_plane_nodes|first].ansible_nodename }}
     --ignore-daemonsets
  register: drain_result
  until: drain_result.rc == 0
  retries: 10
  delay: 30
  changed_when: false

- name: upgrade cluster
  shell: >-
    {{ kubernetes_install_path }}/kubeadm upgrade apply
    {{ upgrade_version }} --force
  register: upgrade_apply_result
  until: upgrade_apply_result.rc == 0
  retries: 10
  delay: 30
  changed_when: false

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: uncordon control plane
  shell: >-
    KUBECONFIG={{ kubernetes_config_path }}/admin.conf
    {{ kubernetes_install_path }}/kubectl uncordon
    {{ hostvars[control_plane_nodes|first].ansible_nodename }}
  register: uncordon_result
  until: uncordon_result.rc == 0
  retries: 10
  delay: 30
  changed_when: false

- name: wait for control plane to become ready
  shell: >-
    KUBECONFIG={{ kubernetes_config_path }}/admin.conf 
    {{ kubernetes_install_path }}/kubectl get nodes | 
    grep {{ hostvars[control_plane_nodes|first].ansible_nodename }} | 
    grep -w Ready
  register: wait_result
  until: wait_result.rc == 0
  retries: 10
  delay: 30
  changed_when: false
