- name: open firewall ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items: "{{ grafana_firewall_ports }}"
  notify: reload firewalld

- name: start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started
