- name: create user group
  group:
    name: "{{ cert_group }}"
  when: cert_group is defined and cert_group != ""

- name: create user
  user:
    name: "{{ cert_owner }}"
  when: cert_owner is defined and cert_owner != ""

- name: create destination directory
  file:
    path: "{{ cert_path }}"
    owner: "{{ cert_owner|default(omit, true) }}"
    group: "{{ cert_group|default(omit, true) }}"
    state: directory

- name: fetch ca certificate
  copy:
    src: "{{ selfsignedcerts_certs_path }}/ca/ca.crt"
    dest: "{{ cert_path }}/ca.crt"
    owner: "{{ cert_owner|default(omit, true) }}"
    group: "{{ cert_group|default(omit, true) }}"
    mode: 0644
