- name: check unseal tokens file exist
  stat:
    path: '{{ vault_config_path }}/.vault_unseal_tokens'
  register: unseal_token_file
  delegate_to: '{{ dest_host }}'

- name: save unseal tokens to file
  copy:
    content: "{{ [unseal_key_1, unseal_key_2, unseal_key_3, unseal_key_4, unseal_key_5, root_token] | join('\n') }}"
    dest: '{{ vault_config_path }}/.vault_unseal_tokens'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: 0640
  when: not unseal_token_file.stat.exists
  no_log: true
  delegate_to: '{{ dest_host }}'
