- name: get list of enabled secret backends
  uri:
    url: >-
      http://127.0.0.1:{{ vault_port }}/v1/sys/mounts
    headers:
      X-Vault-Token: '{{ root_token }}'
  register: check_secret_backends_result

- set_fact:
    enabled_secret_backends: >-
      {{ (check_secret_backends_result.json.data).keys()|list|
        replace('/', '') }}

- set_fact:
    existing_secret_backend_configs: >-
      {{ check_secret_backends_result.json[secret_backend.type + '/'] }}
  when: secret_backend.type in enabled_secret_backends

- name: enable secret backend
  uri:
    url: >-
      http://127.0.0.1:{{ vault_port }}/v1/sys/mounts/{{ secret_backend.type }}
    headers:
      X-Vault-Token: '{{ root_token }}'
    method: POST
    body_format: json
    body: '{{ secret_backend }}'
    status_code: [200, 204]
  register: enable_secret_backend_result
  when: secret_backend.type not in enabled_secret_backends

- block:
    - set_fact:
        description_equal: >-
          {{ existing_secret_backend_configs.description|default('', true) ==
            secret_backend.description|default('', true) }}
        default_lease_ttl_equal: >-
          {{ existing_secret_backend_configs.config.default_lease_ttl|
            default(0, true) == secret_backend.config.default_lease_ttl|
            default(0, true) }}
        max_lease_ttl_equal: >-
          {{ existing_secret_backend_configs.config.max_lease_ttl|
            default(0, true)== secret_backend.config.max_lease_ttl|
            default(0, true) }}
        audit_non_hmac_request_keys_equal: >-
          {{ existing_secret_backend_configs.config.audit_non_hmac_request_keys|
            default([], true)|symmetric_difference(
            secret_backend.config.audit_non_hmac_request_keys|
            default([], true))|length == 0 }}
        audit_non_hmac_response_keys_equal: >-
          {{ existing_secret_backend_configs.config.audit_non_hmac_response_keys|
            default([], true)|symmetric_difference(
            secret_backend.config.audit_non_hmac_response_keys|
            default([], true))|length == 0 }}
        listing_visibility_equal: >-
          {{ existing_secret_backend_configs.config.listing_visibility|
            default('', true) == secret_backend.config.listing_visibility|
            default('', true) }}
        passthrough_request_headers_equal: >-
          {{ existing_secret_backend_configs.config.passthrough_request_headers|
            default([], true)|symmetric_difference(
            secret_backend.config.passthrough_request_headers|
            default([], true))|length == 0 }}
        allowed_response_headers_equal: >-
          {{ existing_secret_backend_configs.config.allowed_response_headers|
            default([], true)|symmetric_difference(
            secret_backend.config.allowed_response_headers|default([], true))|
            length == 0 }}
        request_payload:
          description: '{{ secret_backend.description }}'
          default_lease_ttl: >-
           {{ secret_backend.config.default_lease_ttl|default(0, true) }}
          max_lease_ttl: >-
            {{ secret_backend.config.max_lease_ttl|default(0, true) }}
          audit_non_hmac_request_keys: >-
            {{ secret_backend.config.audit_non_hmac_request_keys|
              default([], true) }}
          audit_non_hmac_response_keys: >-
            {{ secret_backend.config.audit_non_hmac_response_keys|
              default([], true) }}
          listing_visibility: >-
            {{ secret_backend.config.listing_visibility|default('', true) }}
          passthrough_request_headers: >-
            {{ secret_backend.config.passthrough_request_headers|
              default([], true) }}
          allowed_response_headers: >-
            {{ secret_backend.config.allowed_response_headers|
              default([], true) }}

    - name: tune secret backend
      uri:
        url: >-
          http://127.0.0.1:{{ vault_port }}/v1/sys/mounts/{{
            secret_backend.type }}/tune
        headers:
          X-Vault-Token: '{{ root_token }}'
        method: POST
        body_format: json
        body: '{{ request_payload }}'
        status_code: [200, 204]
      register: tune_secret_backend_result
      when: not description_equal or
            not default_lease_ttl_equal or
            not max_lease_ttl_equal or
            not audit_non_hmac_request_keys_equal or
            not audit_non_hmac_response_keys_equal or
            not listing_visibility_equal or
            not passthrough_request_headers_equal or
            not allowed_response_headers_equal
  when: secret_backend.type in enabled_secret_backends
