- firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items: '{{ vault_firewall_ports }}'
  notify: restart firewalld

- name: start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started
