- name: check if vault is initialized
  shell: >-
    VAULT_ADDR=http://127.0.0.1:{{ vault_port }} /usr/local/bin/vault status | 
    grep Initialized | awk '{print $2}'
  register: vault_initialize_check
  changed_when: false

- set_fact:
    vault_initialized: '{{ vault_initialize_check.stdout|bool }}'

- block:
    - name: initialize vault
      uri:
        url: >-
          http://127.0.0.1:{{ vault_port }}/v1/sys/init
        method: PUT
        body_format: json
        body: '{{ vault_initialization_options }}'
      register: vault_initialize_result

    - set_fact:
        unseal_keys: '{{ vault_initialize_result.json.values()|list|first }}'
        init_root_token: '{{ vault_initialize_result.json.values()|list|last }}'

    - name: save unseal keys to file
      copy:
        content: "{{ unseal_keys|join('\n') }}"
        dest: "{{ vault_data_path }}/.vault_unseal_keys"
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: 0600
      no_log: true

    - include_tasks: copyto_unseal_keys.yml
      with_items: >-
        {{ groups[vault_servers_group_name]|
          reject('search', inventory_hostname)|list }}
      loop_control:
        loop_var: dest_host
  when: not vault_initialized
