- name: create vault user group
  group:
    name: '{{ vault_group }}'
    state: present

- name: create vault user
  user:
    name: '{{ vault_user }}'
    comment: Vault user
    group: '{{ vault_group }}'
    shell: /bin/false

- name: create vault directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items:
    - { path: '{{ vault_bin_path }}',
        owner: 'root',
        group: 'root',
        mode: '0755' }
    - { path: '{{ vault_config_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0700' }
    - { path: '{{ vault_data_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0700' }
    - { path: '{{ vault_certs_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0700' }
    - { path: '{{ vault_plugin_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0700' }
    - { path: '{{ vault_run_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0750' }
    - { path: '{{ vault_log_path }}',
        owner: '{{ vault_user }}',
        group: '{{ vault_group }}',
        mode: '0750' }

- name: download vault
  get_url:
    url: '{{ vault_zip_url }}'
    dest: '{{ vault_bin_path }}'
    checksum: 'sha256:{{ vault_zip_checksum }}'

- name: install vault
  unarchive:
    src: >-
      {{ vault_bin_path }}/{{ (vault_zip_url|urlsplit('path')).split('/')[-1] }}
    dest: '{{ vault_bin_path }}'
    remote_src: yes
    validate_certs: no

- name: create vault systemd file
  template:
    src: vault_systemd.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart vault

- name: create vault config file
  template:
    src: vault_config.hcl.j2
    dest: '{{ vault_config_path }}/{{ vault_config_file }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: 0640
  notify: restart vault

- name: start vault
  service:
    name: vault
    enabled: yes
    state: started
