- name: create vault user group
  group:
    name: '{{ vault_group }}'
    state: present

- name: create vault user
  user:
    name: '{{ vault_user }}'
    group: '{{ vault_group }}'
    shell: /bin/false

- name: create vault directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
  with_items:
    - "{{ vault_config_path }}"
    - "{{ vault_data_path }}"
    - "{{ vault_certs_path }}"
    - "{{ vault_plugin_path }}"
    - "{{ vault_run_path }}"
    - "{{ vault_log_path }}"
    - "{{ vault_config_path }}/scripts"

- set_fact:
    vault_src_base_url: >-
      {{- "https://releases.hashicorp.com/vault/" + vault_version|string -}}

- name: download checksum file
  get_url:
    url: "{{ vault_src_base_url }}/vault_{{ vault_version }}_SHA256SUMS"
    dest: /usr/local/src

- name: read checksum from file
  shell: >-
    /bin/grep vault_{{ vault_version }}_linux_amd64.zip
    /usr/local/src/vault_{{ vault_version }}_SHA256SUMS | awk '{print $1}'
  register: checksum
  changed_when: false

- name: download vault
  get_url:
    url: "{{ vault_src_base_url }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /usr/local/src
    checksum: 'sha256:{{ checksum.stdout }}'

- name: install vault
  unarchive:
    src: >-
      /usr/local/src/vault_{{ vault_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    validate_certs: no

- name: create vault systemd file
  template:
    src: vault_systemd.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart vault

- name: create vault config file
  template:
    src: vault_config.hcl.j2
    dest: '{{ vault_config_path }}/{{ vault_config_file }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: 0640
  notify:
    - restart vault

- name: create unseal script
  template:
    src: unseal.sh.j2
    dest: "{{ vault_config_path }}/scripts/unseal.sh"
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: 0744

- name: start vault
  service:
    name: vault
    enabled: yes
    state: started
