- include_tasks: preinstall.yml

- name: install vault
  include_tasks: install.yml

- meta: flush_handlers

- name: initialize and unseal vault
  include_tasks: initialize_unseal.yml
  args:
    apply:
      delegate_to: localhost
  with_items: '{{ groups[vault_servers_group_name] }}'
  loop_control:
    loop_var: hostname
  when: vault_auto_unseal
  run_once: yes

- name: perform after install actions
  include_tasks: postinstall_actions.yml
  args:
    apply:
      delegate_to: "{{ hostname }}"
  with_items: '{{ groups[vault_servers_group_name] }}'
  loop_control:
    loop_var: hostname
  when: vault_auto_unseal
  run_once: yes

- name: turn off swapping
  include_tasks: swaps.yml
  when: vault_swap_off
