- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
  listen: restart alertmanager

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded
  listen: reload alertmanager
