- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted
  listen: restart blackbox_exporter

- name: reload blackbox_exporter
  service:
    name: blackbox_exporter
    state: reloaded
  listen: reload blackbox_exporter
