- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  listen: restart prometheus

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded
  listen: reload prometheus
