---
- name: restart chronyd
  service:
    name: chronyd
    state: restarted
  listen: restart chronyd

- name: restart timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: restarted
