- name: check if primary exist in resource
  shell: /sbin/drbdadm status {{ inner_loop_resource.name }}
  register: check_primary

- set_fact:
    primary_exist: >-
      {{- check_primary.stdout_lines|select('search','role:Primary')|list|
      length > 0|ternary(true, false) -}}
    allow_two_primaries: >-
      {{- drbd_common_conf.net['allow-two-primaries'] is defined or
      inner_loop_resource.net['allow-two-primaries'] is defined|
      default(true, false) -}}

- name: set to primary
  shell: /sbin/drbdadm primary --force {{ inner_loop_resource.name }}
  register: set_primary
  when:
    - "'role:Secondary' in check_primary.stdout_lines[0]"
    - allow_two_primaries

- name: set to primary
  shell: /sbin/drbdadm primary --force {{ inner_loop_resource.name }}
  register: set_primary
  when:
    - "'role:Secondary' in check_primary.stdout_lines[0]"
    - not allow_two_primaries
    - not primary_exist
  failed_when:
    - set_primary.rc != 0
    - "'Multiple primaries not allowed by config' not in set_primary.stderr"
