- name: check if primary exist in resource
  shell: /sbin/drbdadm status {{ inner_loop_resource.name }}
  register: check_primary

- set_fact:
    primary_exist: >-
      {{- check_primary.stdout_lines|select('search','role:Primary')|list|
      length > 0|ternary(true, false) -}}
    allow_two_primaries: >-
      {{- drbd_common_conf.net['allow-two-primaries'] is defined or
      inner_loop_resource.net['allow-two-primaries'] is defined|
      default(true, false) -}}

- name: set primary - dual
  shell: /sbin/drbdadm primary --force {{ inner_loop_resource.name }}
  register: set_dual_primary
  when:
    - "'role:Secondary' in check_primary.stdout_lines[0]"
    - allow_two_primaries

- name: adjust resource
  shell: /sbin/drbdadm drbdadm adjust {{ inner_loop_resource.name }}
  register: adjust_resource
  when:
    - set_dual_primary is changed
    - allow_two_primaries

- name: set primary - single
  shell: /sbin/drbdadm primary --force {{ inner_loop_resource.name }}
  register: set_single_primary
  when:
    - "'role:Secondary' in check_primary.stdout_lines[0]"
    - not allow_two_primaries
    - not primary_exist
  failed_when:
    - set_single_primary.rc != 0
    - "'Multiple primaries not allowed by config' not in 
      set_single_primary.stderr"

- name: wait for sync up to 10 mins
  shell: >-
    /sbin/drbdadm status {{ inner_loop_resource.name }} | grep -w disk |
    awk -F: '{print $2}'
  register: wait_sync
  until: 
    - wait_sync.stdout_lines|unique|count == 1
    - wait_sync.stdout_lines|unique|first == 'UpToDate'
  retries: 20
  delay: 30
  changed_when: false