- name: open firewall ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items: '{{ jenkins_firewall_ports }}'
  notify: reload firewalld

- name: start firewalld
  service:
    name: firewalld
    state: started
