- name: add every hosts to /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^\s*{{ hostvars[item].ansible_host|replace(''.'',''\.'') }}\s+{{ hostvars[item].inventory_hostname|replace(''.'',''\.'') }}'
    line: >-
      {{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname}}
    state: present
    create: yes
  with_items: "{{ groups[jenkins_master_group_name] }}"

- name: remove loopback entry from /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1\s+{{ inventory_hostname }}'
    state: absent

- name: remove loopback entry from /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+{{ inventory_hostname }}'
    state: absent
