---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  listen: restart firewalld

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  listen: reload firewalld
