---
- name: reload systemd
  systemd:
    daemon_reload: true
  listen: reload systemd

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  listen: restart firewalld

- name: restart drbd
  service:
    name: drbd
    state: restarted
  listen: restart drbd

- name: reload drbd
  service:
    name: drbd
    state: reloaded
  listen: reload drbd