- firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items: '{{ haproxy_firewall_ports }}'
  notify: restart firewalld

- name: start firewalld
  service:
    name: firewalld
    state: started
