- name: install build dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ haproxy_build_dependencies }}'

- name: create haproxy user group
  group:
    name: '{{ haproxy_group }}'
    state: present

- name: create haproxy user
  user:
    name: '{{ haproxy_user }}'
    comment: HAProxy user
    group: '{{ haproxy_group }}'
    shell: /sbin/nologin

- name: create haproxy directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items:
    - { path: '{{ haproxy_config_path }}',
        user: '{{ haproxy_user}}',
        group: '{{ haproxy_group }}',
        mode: '0755' }
    - { path: '{{ haproxy_certs_path }}',
        user: '{{ haproxy_user}}',
        group: '{{ haproxy_group }}',
        mode: '0755' }
    - { path: '{{ haproxy_run_path }}',
        user: 'root',
        group: 'root',
        mode: '0755' }
    - { path: '{{ haproxy_chroot_path }}',
        user: 'root',
        group: 'root',
        mode: '0440' }
    - { path: '{{ haproxy_log_path }}',
        user: '{{ haproxy_user}}',
        group: '{{ haproxy_group }}',        
        mode: '0755' }
    - { path: '/usr/local/src',
        user: 'root',
        group: 'root',
        mode: '0755' }

- set_fact:
    haproxy_base_src_url: >-
      {{ "http://www.haproxy.org/download" }}/{{ 
        haproxy_version.split('.')[:-1]|join('.') }}/src

- name: download checksum file
  get_url:
    url: >-
      {{ haproxy_base_src_url }}/haproxy-{{ haproxy_version }}.tar.gz.sha256
    dest: /usr/local/src/

- name: get checksum from file
  slurp:
    src: /usr/local/src/haproxy-{{ haproxy_version }}.tar.gz.sha256
  register: checksum

- name: download haproxy source file
  get_url:
    url: >-
      {{ haproxy_base_src_url }}/haproxy-{{ haproxy_version }}.tar.gz
    dest: /usr/local/src/
    checksum: sha256:{{ (checksum.content|b64decode).split()[0] }}

- name: uncompress haproxy source file
  unarchive:
    src: /usr/local/src/haproxy-{{ haproxy_version }}.tar.gz
    dest: /usr/local/src/
    remote_src: yes
  register: unarchive_result

- name: build and install haproxy
  shell: >-
    make {{ haproxy_build_options|join(' ') }} && make install
  args:
    chdir: /usr/local/src/haproxy-{{ haproxy_version }}
  register: build_result
  when: unarchive_result is changed
  notify: restart haproxy

- name: create haproxy systemd file
  template:
    src: haproxy_systemd.service.j2
    dest: /etc/systemd/system/haproxy.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart haproxy

- name: create haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: '{{ haproxy_config_path }}/{{ haproxy_config_file }}'
    owner: '{{ haproxy_user }}'
    group: '{{ haproxy_group }}'
    mode: 0640
  notify: restart haproxy

- name: start haproxy
  service:
    name: haproxy
    enabled: yes
    state: started
