# - name: install rsyslog
#   package:
#     name: rsyslog
#     state: present

- name: create syslog config file
  template:
    src: haproxy_syslog.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
