---
- name: modify hosts file
  include_tasks: hostsfile.yml
  vars:
    server_groups: "{{ alertmanager_servers_group_name }}"

- name: create alertmanager user group
  group:
    name: "{{ alertmanager_group }}"
    state: present

- name: create alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    shell: /sbin/nologin

- name: create alertmanager directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0755
  with_items:
    - { path: "{{ alertmanager_config_path }}",
        owner: "{{ alertmanager_user}}",
        group: "{{ alertmanager_group }}" }
    - { path: "{{ alertmanager_config_path }}/templates",
        owner: "{{ alertmanager_user}}",
        group: "{{ alertmanager_group }}" }
    - { path: "{{ alertmanager_data_path }}",
        owner: "{{ alertmanager_user}}",
        group: "{{ alertmanager_group }}" }
    - { path: "{{ alertmanager_certs_path }}",
        owner: "{{ alertmanager_user }}",
        group: "{{ alertmanager_group }}" }
    - { path: "{{ alertmanager_log_path }}",
        owner: "{{ alertmanager_user}}",
        group: "{{ alertmanager_group }}" }
    - { path: "{{ alertmanager_bin_path }}",
        owner: root,
        group: root }
    - { path: /usr/local/src,
        owner: root,
        group: root }

- name: download alertmanager binary package
  get_url:
    url: "{{ alertmanager_src_url }}"
    dest: /usr/local/src/
    checksum: sha256:{{ alertmanager_src_checksum }}
  register: download_result

- set_fact:
    source_filename: >-
      {{ alertmanager_src_url|urlsplit('path')|basename }}

- block:
    - name: uncompress alertmanager binary package
      unarchive:
        src: /usr/local/src/{{ source_filename }}
        dest: /usr/local/src/
        remote_src: yes

    - set_fact:
        dirname: "{{ source_filename.split('.')[:-2]|join('.') }}"

    - name: copy alertmanager binary files
      copy:
        src: /usr/local/src/{{ dirname }}/{{ item }}
        dest: "{{ alertmanager_bin_path }}/{{ item }}"
        owner: "{{ alertmanager_user }}"
        group: "{{ alertmanager_group }}"
        mode: 0755
        remote_src: yes
      with_items:
        - alertmanager
        - amtool
  when: download_result is changed

- name: create alertmanager systemd file
  template:
    src: alertmanager_systemd.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart alertmanager

- name: create alertmanager config file
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_path }}/{{ alertmanager_config_file }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640
  notify: restart alertmanager

- name: start alertmanager
  service:
    name: alertmanager
    enabled: yes
    state: started
