- name: open {{ prometheus_component }} firewall ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  with_items: "{{ firewall_ports }}"
  notify: restart firewalld

- name: start firewalld
  service:
    name: firewalld
    state: started
