- name: install and enable firewalld
  include_tasks: firewalld.yml
  vars:
    prometheus_component: mysqld_exporter
    firewall_ports: "{{ mysqld_exporter_firewall_ports }}"

- name: create mysqld exporter user group
  group:
    name: '{{ mysqld_exporter_group }}'
    state: present

- name: create mysqld exporter user
  user:
    name: '{{ mysqld_exporter_user }}'
    group: '{{ mysqld_exporter_group }}'
    shell: /sbin/nologin

- name: create mysqld exporter directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{ mysqld_exporter_config_path }}',
        user: '{{ mysqld_exporter_user }}',
        group: '{{ mysqld_exporter_group }}',
        mode: '0755' }
    - { path: '{{ mysqld_exporter_log_path }}',
        user: '{{ mysqld_exporter_user }}',
        group: '{{ mysqld_exporter_group }}',
        mode: '0755' }

- name: download mysqld exporter binary package
  get_url:
    url: '{{ mysqld_exporter_src_url }}'
    dest: /usr/local/src
    checksum: 'sha256:{{ mysqld_exporter_src_checksum }}'
  register: download_result

- set_fact:
    source_filename: >-
      {{ mysqld_exporter_src_url|urlsplit('path')|basename }}

- block:
    - name: uncompress mysqld exporter binary package
      unarchive:
        src: /usr/local/src/{{ source_filename }}
        dest: /usr/local/src
        remote_src: yes

    - set_fact:
        dirname: "{{ source_filename.split('.')[:-2]|join('.') }}"

    - name: copy mysqld exporter binary files
      copy:
        src: /usr/local/src/{{ dirname }}/mysqld_exporter
        dest: "{{ mysqld_exporter_bin_path }}/mysqld_exporter"
        owner: "{{ mysqld_exporter_user }}"
        group: "{{ mysqld_exporter_group }}"
        mode: 0755
        remote_src: yes
  when: download_result is changed

- name: create mysqld exporter systemd file
  template:
    src: mysqld_exporter_systemd.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart mysqld_exporter

- name: create mysql credential config file
  template:
    src: mysql.cnf.j2
    dest: "{{ mysqld_exporter_config_path }}/{{ mysqld_exporter_mysql_file }}"
    owner: "{{ mysqld_exporter_user }}"
    group: "{{ mysqld_exporter_group }}"
    mode: 0600
  notify: restart mysqld_exporter

- name: start mysqld_exporter
  service:
    name: mysqld_exporter
    state: started

- name: configure logrotate
  include_tasks: logrotate.yml
  vars:
    prometheus_component: mysqld_exporter
    logrotate_config: "{{ mysqld_exporter_logrotate_config }}"
