---
- name: create node exporter user group
  group:
    name: "{{ node_exporter_group }}"
    state: present

- name: create node exporter user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    shell: /sbin/nologin

- name: create node exporter directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0755
  with_items:
    - { path: "{{ node_exporter_log_path }}",
        owner: "{{ node_exporter_user}}",
        group: "{{ node_exporter_group }}" }
    - { path: "{{ node_exporter_bin_path }}",
        owner: root,
        group: root }
    - { path: /usr/local/src,
        owner: root,
        group: root }

- name: download node exporter binary package
  get_url:
    url: "{{ node_exporter_src_url }}"
    dest: /usr/local/src/
    checksum: sha256:{{ node_exporter_src_checksum }}
  register: download_result

- set_fact:
    source_filename: >-
      {{ node_exporter_src_url|urlsplit('path')|basename }}

- block:
    - name: uncompress node exporter binary package
      unarchive:
        src: /usr/local/src/{{ source_filename }}
        dest: /usr/local/src/
        remote_src: yes

    - set_fact:
        dirname: "{{ source_filename.split('.')[:-2]|join('.') }}"

    - name: copy node exporter binary files
      copy:
        src: /usr/local/src/{{ dirname }}/node_exporter
        dest: "{{ node_exporter_bin_path }}/node_exporter"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: 0755
        remote_src: yes
  when: download_result is changed

- name: create node exporter systemd file
  template:
    src: node_exporter_systemd.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter

- name: start node_exporter
  service:
    name: node_exporter
    enabled: yes
    state: started
