- name: install and enable firewalld
  include_tasks: firewalld.yml
  vars:
    prometheus_component: statsd_exporter
    firewall_ports: "{{ statsd_exporter_firewall_ports }}"

- name: create statsd exporter user group
  group:
    name: '{{ statsd_exporter_group }}'
    state: present

- name: create statsd exporter user
  user:
    name: '{{ statsd_exporter_user }}'
    group: '{{ statsd_exporter_group }}'
    shell: /sbin/nologin

- name: create statsd exporter log directory
  file:
    path: '{{ statsd_exporter_log_path }}'
    state: directory
    owner: '{{ statsd_exporter_user }}'
    group: '{{ statsd_exporter_group }}'
    mode: 0755

- name: download statsd exporter binary package
  get_url:
    url: '{{ statsd_exporter_src_url }}'
    dest: /usr/local/src
    checksum: 'sha256:{{ statsd_exporter_src_checksum }}'
  register: download_result

- set_fact:
    source_filename: >-
      {{ statsd_exporter_src_url|urlsplit('path')|basename }}

- block:
    - name: uncompress statsd exporter binary package
      unarchive:
        src: /usr/local/src/{{ source_filename }}
        dest: /usr/local/src
        remote_src: yes

    - set_fact:
        dirname: "{{ source_filename.split('.')[:-2]|join('.') }}"

    - name: copy statsd exporter binary files
      copy:
        src: /usr/local/src/{{ dirname }}/statsd_exporter
        dest: "{{ statsd_exporter_bin_path }}/statsd_exporter"
        owner: "{{ statsd_exporter_user }}"
        group: "{{ statsd_exporter_group }}"
        mode: 0755
        remote_src: yes
  when: download_result is changed

- name: create statsd exporter systemd file
  template:
    src: statsd_exporter_systemd.service.j2
    dest: /etc/systemd/system/statsd_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart statsd_exporter

- name: start statsd_exporter
  service:
    name: statsd_exporter
    enabled: yes
    state: started

- name: configure logrotate
  include_tasks: logrotate.yml
  vars:
    prometheus_component: statsd_exporter
    logrotate_config: "{{ statsd_exporter_logrotate_config }}"
