- name: setup drbd cluster
  hosts: drbd_servers
  become: yes
  roles:
    - name: ntp
    - name: rsyslog
      vars:
        rsyslog_configurations:
          - name: drbd.conf
            configuration: |-
              if $programname == "drbd" or ($syslogtag == "kernel:" and
              $msg contains "drbd") then {
                  action(type="omfile" file="{{ drdb_log_path }}/{{ drbd_log_file }}")
                  stop
              }
    - name: firewalld
      vars:
        firewalld_ports:
          - "{{ drbd_listen_ports }}/tcp"
    - name: drbd
      vars:
        drbd_resources_conf:
          - name: drbd1
            meta-disk: internal
            device: /dev/drbd1
            disk: /dev/sdb1
            net:
              verify-alg: sha256
              #allow-two-primaries: 'yes'
            'on':
              - name: drbd1.cluster.local
                node-id: 0
                address: 192.168.3.206:7788
              - name: drbd2.cluster.local
                node-id: 1
                address: 192.168.3.207:7788
            connection-mesh:
              hosts: drbd1.cluster.local drbd2.cluster.local
