---
- name: sync clock
  hosts: prometheus_servers
  become: yes
  roles:
    - name: chrony

- name: setup drbd for prometheus cluster
  hosts: prometheus_servers
  become: yes
  vars:
    keepalived_vip: 192.168.3.100
  roles:
    - name: drbd
      vars:
        drbd_servers_group_name: prometheus_servers
        drbd_resources_conf:
          - name: drbd1
            meta-disk: internal
            device: /dev/drbd1
            disk: /dev/sdb1
            options:
              auto-promote: 'no'
            net:
              verify-alg: sha256
            'on':
              - name: prometheus1.cluster.local
                node-id: 0
                address: 192.168.3.210:7788
              - name: prometheus2.cluster.local
                node-id: 1
                address: 192.168.3.211:7788
            connection-mesh:
              hosts: prometheus1.cluster.local prometheus2.cluster.local
  post_tasks:
    - name: prepare resource device
      include_role:
        name: drbd
        tasks_from: prep_resource_device
      vars:
        mountpoint_path: /var/lib/prometheus
        mountpoint_owner: prometheus
        mountpoint_group: prometheus
        resource_device: /dev/drbd1
        resource_device_filesystem: xfs

    - name: create drbd before demote script
      copy:
        content: |
          /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > /dev/null
          if [ $? -eq 0 ]; then
              echo "Skipping demote. keepalived VIP is attached."
              exit 1
          fi

          # stop prometheus
          /bin/systemctl stop prometheus

          # wait for prometheus to stop
          loop_max=10
          loop_count=0
          while [ -n "`/sbin/pidof prometheus`" ] && 
          [ $loop_count -lt $loop_max ]; do
              echo "waiting for prometheus to stop"
              sleep 10
              loop_count=$((loop_count + 1))
          done

          if [ $loop_count -ge $loop_max ]; then
              echo "unable to stop prometheus"
              exit
          fi
        dest: "{{ drdb_script_path }}/pre_demote.sh"
        owner: root
        group: root
        mode: 0744

    - name: create drbd after demote script
      copy:
        content: |
          # start prometheus
          /bin/systemctl start prometheus

          # wait for prometheus to start
          loop_max=10
          loop_count=0
          stat_code=$(/bin/curl -o /dev/null -s -w "%{http_code}\n" \
          http://localhost:9090/status)
          while [ $stat_code -ne 200 ] && [ $loop_count -lt $loop_max ]; do
              echo "waiting for prometheus to start"
              stat_code=$(/bin/curl -o /dev/null -s -w "%{http_code}\n" \
              http://localhost:9090/status)
              loop_count=$((loop_count + 1))
              sleep 10
          done
        dest: "{{ drdb_script_path }}/post_demote.sh"
        owner: root
        group: root
        mode: 0744

    - name: create drbd before promote script
      copy:
        content: |
          /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > /dev/null
          if [ $? -ne 0 ]; then
              echo "Skipping promote. keepalived VIP is not attached."
              exit 1
          fi
        dest: "{{ drdb_script_path }}/pre_promote.sh"
        owner: root
        group: root
        mode: 0744

    - name: create drbd after successful promote script
      copy:
        content: |
          /bin/mount | grep -w drbd1
          if [ $? -eq 0 ]; then
              echo "prometheus volume already mounted"
          else
              echo "mounting prometheus volume" 
              /bin/mount /dev/drbd1 /var/lib/prometheus
          fi

          echo "restarting prometheus server"
          /bin/systemctl restart prometheus

          # wait for prometheus to start
          loop_max=10
          loop_count=0
          stat_code=$(/bin/curl -o /dev/null -s -w "%{http_code}\n" \
          http://localhost:9090/status)
          while [ $stat_code -ne 200 ] && [ $loop_count -lt $loop_max ]; do
              echo "waiting for prometheus to start"
              stat_code=$(/bin/curl -o /dev/null -s -w "%{http_code}\n" \
              http://localhost:9090/status)
              loop_count=$((loop_count + 1))
              sleep 10
          done
        dest: "{{ drdb_script_path }}/post_promote.sh"
        owner: root
        group: root
        mode: 0744

    - name: create drbd after failed promote script
      copy:
        content: |
          /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > /dev/null
          if [ $? -eq 0 ]; then
              /bin/systemctl stop prometheus
          fi

          while true
          do
              /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > \
              /dev/null
              if [ $? -ne 0 ]; then
                  /bin/systemctl start prometheus
                  break
              fi

              sleep 5
          done
        dest: "{{ drdb_script_path }}/failed_promote.sh"
        owner: root
        group: root
        mode: 0744

- name: setup prometheus cluster
  hosts: prometheus_servers
  become: yes
  roles:
    - name: prometheus
      include_vars: defaults/node_exporter.yml
      vars:
        prometheus_components:
          alertmanager:
            installed: true
          node_exporter:
            installed: true
        prometheus_scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets: >-
                  {%- set servers = [] -%}
                  {%- for server in groups[prometheus_servers_group_name] -%}
                    {{- servers.append(server + ':' + 
                    prometheus_web_listen_port|string) -}}
                  {%- endfor-%}
                  {{- servers -}}
          - job_name: node exporters
            static_configs:
              - targets: >-
                  {%- set servers = [] -%}
                  {%- for server in groups[prometheus_servers_group_name] -%}
                    {{- servers.append(server + ':' + 
                    node_exporter_web_listen_port|string) -}}
                  {%- endfor-%}
                  {{- servers -}}
        prometheus_alertmanager_config:
          - static_configs:
            - targets: >-
                  {%- set servers = [] -%}
                  {%- for server in groups[prometheus_servers_group_name] -%}
                    {{- servers.append(server + ':' + 
                    alertmanager_web_listen_port|string) -}}
                  {%- endfor-%}
                  {{- servers -}}
        alertmanager_servers_group_name: prometheus_servers
        alertmanager_route_config:
          group_by:
            - alertname
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1h
          receiver: web.hook
        alertmanager_receivers_config:
          - name: web.hook
            webhook_configs:
            - url: http://127.0.0.1:5001/

- name: setup keepalived for prometheus cluster
  hosts: prometheus_servers
  become: yes
  pre_tasks:
    - name: create keepalived script directory
      file:
        path: "{{ keepalived_scripts_path }}"
        state: directory

    - name: create prometheus check script
      copy:
        content: |-
          #!/bin/bash

          stat_code=$(/bin/curl -o /dev/null -s -w "%{http_code}\n" \
          http://localhost:9090/status)

          if [ $stat_code -eq 200 ]; then
              exit 0
          else
              exit 1
          fi
        dest: "{{ keepalived_config_path }}/scripts/chk_prometheus.sh"
        owner: root
        group: root
        mode: 0744
      register: prometheus_chk_script
  roles:
    - name: keepalived
      vars:
        keepalived_vip: 192.168.3.100
        keepalived_network: >-
          {{ keepalived_vip.split('.')[:-1]|join('.') + '.0' }}
        keepalived_configs:
          global_defs:
            script_user: root root
            enable_script_security:
            notification_email:
              - email@example.com
          vrrp_script:
            - name: chk_prometheus
              script: "{{ keepalived_config_path }}/scripts/chk_prometheus.sh"
              interval: 30
              weight: 2
          vrrp_instance:
            - name: PROMETHEUS_HA
              interface: |-
                {%- for key, value in ansible_facts.items() if
                  value.ipv4.network is defined and
                  value.ipv4.network == keepalived_network -%}
                {{- key -}}
                {%- endfor -%}
              state: >-
                {{- 'MASTER' if groups.prometheus_servers|
                first == inventory_hostname else 'BACKUP' -}}
              priority: >-
                {%- for hostname in groups.prometheus_servers|reverse -%}
                  {%- if hostname == inventory_hostname -%}
                    {{- loop.index -}}
                  {%- endif -%}
                {%- endfor -%}
              virtual_router_id: 1
              smtp_alert:
              authentication:
                auth_type: PASS
                auth_pass: mypassword
              unicast_src_ip: >-
                {%- for key, value in ansible_facts.items() if
                  value.ipv4.network is defined and
                  value.ipv4.network == keepalived_network -%}
                {{- value.ipv4.address -}}
                {%- endfor -%}
              unicast_peer: >-
                {%- set servers = [] -%}
                {%- for hostname in groups.prometheus_servers if
                  hostname != inventory_hostname -%}
                  {%- for key, value in hostvars[hostname].ansible_facts.items() if
                    value.ipv4.network is defined and
                    value.ipv4.network == keepalived_network -%}
                    {{- servers.append(value.ipv4.address) -}}
                  {%- endfor -%}
                {%- endfor -%}
                {{- servers -}}
              virtual_ipaddress:
                - "{{ keepalived_vip }}"
              track_script:
                - chk_prometheus
              notify: "{{ keepalived_scripts_path }}/promote_or_demote.sh"
  post_tasks:
    - name: reload keepalived
      service:
        name: keepalived
        state: reloaded
      when: prometheus_chk_script is changed

    - name: create cron job for demoting or promoting drbd resource
      copy:
        content: |
          #!/bin/bash

          if [ -n "`pidof -x $(basename $0) -o %PPID`" ]; then
              echo "$(basename $0) is already running."
              exit
          fi

          role=$(/sbin/drbdadm role all)

          /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > /dev/null
          if [ $? -eq 0 ] && [ "$role" == "Secondary" ]; then
              echo "Promoting to primary."
              /etc/drbd.d/scripts/promote_to_primary.sh
          fi

          /sbin/ip --brief add | /bin/grep -w {{ keepalived_vip }} > /dev/null
          if [ $? -ne 0 ] && [ "$role" == "Primary" ]; then
              echo "Demote to secondary."
              /etc/drbd.d/scripts/demote_to_secondary.sh
          fi
        dest: "{{ keepalived_scripts_path }}/promote_or_demote.sh"
        owner: root
        group: root
        mode: 0744

    - name: create cron job to promote or demote
      cron:
        name: "promote or demote drbd"
        minute: "*/1"
        job: "{{ keepalived_scripts_path }}/promote_or_demote.sh"
