---
- name: setup consul cluster
  hosts: consul_servers
  become: yes
  vars:
  roles: 
    - name: ntp
    - name: firewalld
      vars:
        firewalld_ports:
          - 8600/tcp
          - 8600/udp
          - 8500-8501/tcp
          - 8301-8302/tcp
          - 8301-8302/udp
          - 8300/tcp
          - 21000-21255/tcp
    - name: logrotate
      vars:
        logrotate_config_options:
          - name: consul
            paths:
              - "{{ consul_log_path }}/*.log"
            options:
              - daily
              - missingok
              - rotate 7
              - dateext
              - copytruncate
              - |-
                postrotate
                    /usr/bin/systemctl reload consul
                endscript
    - name: consul
      vars:
        consul_config_options:
          enable_local_script_checks: true
          leave_on_terminate: true
          rejoin_after_leave: true
          log_level: INFO
          log_rotate_max_files: 7
          ui: true
          dns_config:
            enable_truncate: true
            only_passing: true
          acl:
            enabled: true
            enable_token_persistence: true
            default_policy: deny
          connect:
            enabled: true
          ca_file: >-
            {{ consul_certs_path }}/certs/{{ consul_domain }}-agent-ca.pem
          cert_file: >-
            {{ consul_certs_path }}/certs/{{ consul_datacenter }}-server-{{
            consul_domain }}-0.pem
          key_file: >-
            {{ consul_certs_path }}/keys/{{ consul_datacenter }}-server-{{
            consul_domain }}-0-key.pem
          verify_incoming: true
          verify_outgoing: true
          verify_incoming_rpc: true
          verify_server_hostname: true
          encrypt: KVEWESv8Odqmlrn3BXMkHMnrFhkTEtIXk+ZXYqYvzYY=
          auto_encrypt:
            allow_tls: true
        consul_acl_policies:
          - Name: vault_policy
            Description: Policy for Vault access
            Rules: |-
              key_prefix "vault/" {
                policy = "write"
              }
              node_prefix "" {
                policy = "write"
              }
              service "vault" {
                policy = "write"
              }
              agent_prefix "" {
                policy = "write"
              }
              session_prefix "" {
                policy = "write"
              }
          - Name: consul_agent_policy
            Description: Policy for Consul agent node
            Rules: |-
              agent_prefix "" {
                policy = "write"
              }
              node_prefix "" {
                policy = "write"
              }
              service_prefix "" {
                policy = "read"
              }
              session_prefix "" {
                policy = "read"
              }
        consul_acl_tokens:
          - SecretID: cc542a4d-3207-44a4-9d73-c0ac840439e9
            Description: Token for Vault access
            Policies:
              - Name: vault_policy
          - SecretID: 87106a90-47e3-43eb-b1ca-86eec7ca1497
            Description: Token for Consul agent
            Policies:
              - Name: consul_agent_policy
  post_tasks:
    - name: get consul ca certificate from one of the consul server
      fetch:
        src: "{{ consul_certs_path }}/certs/{{ consul_domain }}-agent-ca.pem"
        dest: /tmp/{{ consul_domain }}-agent-ca.pem
        flat: yes
      run_once: yes

- name: setup vault cluster
  hosts: vault_servers
  become: yes
  pre_tasks:
    - name: create consul user group
      group:
        name: consul
        state: present

    - name: create consul user
      user:
        name: consul
        group: consul

    - name: create consul tls directory
      file:
        path: /etc/consul/consul.d/tls
        state: directory
        owner: consul
        group: consul

    - name: copy consul ca certificate to vault servers
      copy:
        src: /tmp/consul-agent-ca.pem
        dest: /etc/consul/consul.d/tls/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0644
  roles: 
    - name: ntp
    - name: firewalld
      vars:
        firewalld_ports:
          - 8200/tcp
          - 8201/tcp
          - 8301/tcp
          - 8301/udp
    - name: logrotate
      vars:
        logrotate_config_options:
          - name: vault
            paths:
              - "{{ vault_log_path }}/*.log"
            options:
              - daily
              - missingok
              - rotate 7
              - dateext
              - copytruncate
              - |-
                postrotate
                    /usr/bin/systemctl reload vault
                endscript
          - name: consul
            paths:
              - "{{ consul_log_path }}/*.log"
            options:
              - daily
              - missingok
              - rotate 7
              - dateext
              - copytruncate
              - |-
                postrotate
                    /usr/bin/systemctl reload consul
                endscript
    - name: consul
      vars:
        consul_config_options:
          leave_on_terminate: true
          rejoin_after_leave: true
          log_level: INFO
          log_rotate_max_files: 7
          acl:
            enabled: true
            enable_token_persistence: true
            default_policy: deny
            tokens:
              agent: 87106a90-47e3-43eb-b1ca-86eec7ca1497
          auto_encrypt:
            tls: true
          ca_file: '{{ consul_certs_path }}/{{ consul_domain }}-agent-ca.pem'
          verify_incoming: true
          verify_outgoing: true
          verify_incoming_rpc: true
          verify_server_hostname: true
          encrypt: KVEWESv8Odqmlrn3BXMkHMnrFhkTEtIXk+ZXYqYvzYY=
          start_join: >-
            {{- groups.consul_servers|map('extract', hostvars, 'ansible_host')|
              list -}}
          retry_join: >-
            {{- groups.consul_servers|map('extract', hostvars, 'ansible_host')|
              list -}}
        consul_agent_mode: client
    - name: vault
      vars:
        vault_auto_unseal: true
        vault_config_options:
          ui: true
          listener:
            - tcp:
                address: "{{ ansible_host}}:{{ vault_port }}"
                cluster_address: "{{ ansible_host }}:{{ vault_cluster_port }}"
                tls_disable: true
          storage:
            consul:
              address: 127.0.0.1:8500
              token: cc542a4d-3207-44a4-9d73-c0ac840439e9
          api_addr: http://{{ ansible_host}}:{{ vault_port }}
          cluster_addr: 'https://{{ ansible_host }}:{{ vault_cluster_port }}'
          log_level: info
          log_format: standard
          pid_file: '{{ vault_run_path }}/vault.pid'
        vault_policies:
          - name: vault_admin
            policy: |-
              path "sys/health"
              {
                capabilities = ["read", "sudo"]
              }

              path "sys/policies/acl"
              {
                capabilities = ["list"]
              }

              path "sys/policies/acl/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "auth/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/auth/*"
              {
                capabilities = ["create", "update", "delete", "sudo"]
              }

              path "sys/auth"
              {
                capabilities = ["read"]
              }

              path "secret/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/mounts/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/mounts"
              {
                capabilities = ["read"]
              }

              path "kv/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
        vault_userpass_users:
          - username: vault_admin
            password: mypassword
            token_policies:
              - vault_admin

- name: setup haproxy cluster for vault and consul
  hosts: haproxy_servers
  become: yes
  pre_tasks:
    - name: allow binding of non-existing ip address
      include_role:
        name: keepalived
        tasks_from: sysctl
  roles:
    - name: ntp
    - name: firewalld
      vars:
        firewalld_ports:
          - 8404/tcp
          - 8500/tcp
          - 8200/tcp
        firewalld_rich_rules:
          - rule protocol value='vrrp' accept
    - name: logrotate
      vars:
        logrotate_config_options:
          - name: haproxy
            paths:
              - /var/log/haproxy/*.log
            options:
              - daily
              - missingok
              - rotate 7
              - dateext
              - copytruncate
              - |-
                postrotate
                    /usr/bin/systemctl reload haproxy
                endscript
          - name: keepalived
            paths:
              - /var/log/keepalived/*.log
            options:
              - daily
              - missingok
              - rotate 7
              - dateext
              - copytruncate
              - |-
                postrotate
                    /usr/bin/systemctl reload keepalived
                endscript
    - name: haproxy
      vars:
        haproxy_defaults_config:
          timeout:
            - connect 10s
            - client 30s
            - server 30s
          log: global
          mode: http
          option: httplog
        haproxy_frontends_config:
          consul.cluster.local:
            bind: 192.168.3.100:8500
            acl:
              - header_host_hostname hdr(host) -i -m beg consul.example.com
              - header_host_ip hdr(host) -i -m beg 192.168.3.100
            use_backend: >-
              consul_servers if header_host_hostname || header_host_ip
          vault.cluster.local:
            bind: 192.168.3.100:8200
            acl:
              - header_host_hostname hdr(host) -i -m beg vault.example.com
              - header_host_ip hdr(host) -i -m beg 192.168.3.100
            use_backend: >-
              vault_servers if header_host_hostname || header_host_ip
        haproxy_backends_config:
          consul_servers:
            balance: roundrobin
            option: httpchk GET /v1/status/leader
            default-server: check inter 10s
            server: >-
              {%- set servers = [] -%}
              {%- for hostname in groups.consul_servers -%}
              {{ servers.append(hostname + ' ' +
                hostvars[hostname].ansible_host + ':' + '8500') }}
              {%- endfor -%}
              {{ servers }}
          vault_servers:
            balance: roundrobin
            option: httpchk GET /v1/sys/health
            http-check: expect status 200,429
            default-server: check inter 10s
            server: >-
              {%- set servers = [] -%}
              {%- for hostname in groups.vault_servers -%}
              {{ servers.append(hostname + ' ' +
                hostvars[hostname].ansible_host + ':' + '8200') }}
              {%- endfor -%}
              {{ servers }}
    - name: keepalived
      vars:
        keepalived_vip: 192.168.3.100
        keepalived_network: >-
          {{ keepalived_vip.split('.')[:-1]|join('.') + '.0' }}
        keepalived_configs:
          global_defs:
            script_user: root root
            enable_script_security:
            notification_email:
              - email@example.com
          vrrp_script:
            - name: chk_haproxy
              script: "'/usr/sbin/pidof haproxy'"
              interval: 5
              weight: 2
          vrrp_instance:
            - name: HAPROXY_LB
              interface: |-
                {%- for key, value in ansible_facts.items() if 
                  value.ipv4.network is defined and 
                  value.ipv4.network == keepalived_network -%}
                {{- key -}}
                {%- endfor -%}
              state: >-
                {{- 'MASTER' if groups.haproxy_servers|first == 
                inventory_hostname else 'BACKUP' -}}
              priority: >-
                {%- for hostname in groups.haproxy_servers|reverse -%}
                  {%- if hostname == inventory_hostname -%}
                    {{- loop.index -}}
                  {%- endif -%}
                {%- endfor -%}
              virtual_router_id: 2
              smtp_alert:
              authentication:
                auth_type: PASS
                auth_pass: mypassword
              unicast_src_ip: >-
                {%- for key, value in ansible_facts.items() if 
                  value.ipv4.network is defined and 
                  value.ipv4.network == keepalived_network -%}
                {{- value.ipv4.address -}}
                {%- endfor -%}
              unicast_peer: >-
                {%- set servers = [] -%}
                {%- for hostname in groups.haproxy_servers if 
                  hostname != inventory_hostname -%}
                  {%- for key, value in hostvars[hostname].ansible_facts.items() if
                    value.ipv4.network is defined and 
                    value.ipv4.network == keepalived_network -%}
                    {{- servers.append(value.ipv4.address) -}}
                  {%- endfor -%}
                {%- endfor -%}
                {{- servers -}}
              virtual_ipaddress:
                - "{{ keepalived_vip }}"
              track_script:
                - chk_haproxy
