---
- name: generate certificates
  hosts: localhost
  become: yes
  roles:
    - name: letsencrypt
      vars:
        letsencrypt_acme_email: email@example.com
        letsencrypt_aws_access_key: my_aws_access_key
        letsencrypt_aws_secret_key: my_aws_secret_key
        letsencrypt_route53_zone: example.com
        letsencrypt_certificates:
          - common_name: example.com
            subject_alt_name:
              - vault.example.com
            valid_days: 7
    - name: selfsignedcerts
      vars:
        selfsignedcerts_server_certificates:
          - common_name: vault1.cluster.local
            subject_alt_names:
              - IP:192.168.1.11
          - common_name: vault2.cluster.local
            subject_alt_names:
              - IP:192.168.2.11
          - common_name: vault3.cluster.local
            subject_alt_names:
              - IP:192.168.3.11
          - common_name: haproxy1.cluster.local
            subject_alt_names:
              - IP:192.168.1.250
          - common_name: haproxy2.cluster.local
            subject_alt_names:
              - IP:192.168.2.250

- name: sync clock
  hosts: vault_servers
  become: yes
  roles:
    - name: chrony

- name: setup vault cluster
  hosts: vault_servers
  become: yes
  pre_tasks:
    - name: copy self signed certificates
      include_role:
        name: selfsignedcerts
        tasks_from: fetch_certskeys.yml
      vars:
        cert_path: "{{ vault_certs_path }}"
        cert_owner: "{{ vault_user }}"
        cert_group: "{{ vault_group }}"
      register: copy_self_signed_certs
  roles:
    - name: vault
      vars:
        vault_config_options:
          ui: true
          listener:
            - tcp:
                address: "{{ ansible_host}}:{{ vault_port }}"
                cluster_address: "{{ ansible_host }}:{{ vault_cluster_port }}"
                tls_client_ca_file: >-
                  {{ vault_certs_path }}/ca.crt
                tls_cert_file: >-
                  {{ vault_certs_path }}/{{ inventory_hostname }}.crt
                tls_key_file: >-
                  {{ vault_certs_path }}/{{ inventory_hostname }}.key
          storage:
            raft:
              path: "{{ vault_data_path }}"
              node_id: "{{ ansible_hostname }}"
              retry_join: >-
                {%- set peers = [] -%}
                {%- for hostname in groups[vault_servers_group_name] if 
                  hostname != inventory_hostname -%}
                  {{- peers.append({"leader_api_addr": 'https://' + 
                  hostvars[hostname].ansible_host + ':' + vault_port|string,
                  "leader_ca_cert_file": vault_certs_path + "/ca.crt",
                  "leader_client_cert_file": vault_certs_path + '/' + 
                  inventory_hostname + ".crt","leader_client_key_file": 
                  vault_certs_path + '/' + inventory_hostname + ".key"}) -}}
                {%- endfor -%}
                {{- peers -}}
          api_addr: http://{{ ansible_host}}:{{ vault_port }}
          cluster_addr: "https://{{ ansible_host }}:{{ vault_cluster_port }}"
          log_level: info
          log_format: standard
          pid_file: "{{ vault_run_path }}/vault.pid"
          disable_mlock: true
        vault_swap_off: true
        vault_policies:
          - name: vault_admin
            policy: |-
              path "sys/health"
              {
                capabilities = ["read", "sudo"]
              }

              path "sys/policies/acl"
              {
                capabilities = ["list"]
              }

              path "sys/policies/acl/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "auth/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/auth/*"
              {
                capabilities = ["create", "update", "delete", "sudo"]
              }

              path "sys/auth"
              {
                capabilities = ["read"]
              }

              path "secret/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/mounts/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/mounts"
              {
                capabilities = ["read"]
              }

              path "kv/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/storage/*"
              {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
        vault_userpass_users:
          - username: vault_admin
            password: mypassword
            token_policies:
              - vault_admin
  post_tasks:
    - name: reload vault
      service:
        name: vault
        state: reloaded
      when: copy_self_signed_certs is changed

- name: setup haproxy cluster for vault
  hosts: haproxy_servers
  become: yes
  pre_tasks:
    - name: allow binding of non-existing ip address
      include_role:
        name: keepalived
        tasks_from: sysctl

    - name: copy letsencrypt certificates to haproxy servers
      include_role:
        name: letsencrypt
        tasks_from: fetch_certificates.yml
      vars:
        cert_path: "{{ haproxy_certs_path }}"
        cert_owner: "{{ haproxy_user }}"
        cert_group: "{{ haproxy_group }}"
        domain_name: example.com

    - name: copy self signed certificates
      include_role:
        name: selfsignedcerts
        tasks_from: fetch_certskeys.yml
      vars:
        cert_path: "{{ haproxy_certs_path }}"
        cert_owner: "{{ haproxy_user }}"
        cert_group: "{{ haproxy_group }}"
      register: copy_self_signed_certs
  roles:
    - name: haproxy
      vars:
        haproxy_defaults_config:
          timeout:
            - connect 10s
            - client 30s
            - server 30s
          log: global
          mode: http
          option: httplog
        haproxy_frontends_config:
          vault_cluster:
            bind: >-
              192.168.3.100:8200 ssl crt
              {{ haproxy_certs_path }}/example.com.pem
            acl:
              - header_host_hostname hdr(host) -i -m beg vault.example.com
              - header_host_ip hdr(host) -i -m beg 192.168.3.100
            use_backend: >-
              vault_servers if header_host_hostname || header_host_ip
        haproxy_backends_config:
          vault_servers:
            balance: roundrobin
            option: httpchk GET /v1/sys/health
            http-check: expect status 200,429
            default-server: >-
              check inter 10s ssl ca-file {{ haproxy_certs_path }}/ca.crt
            server: >-
              {%- set servers = [] -%}
              {%- for hostname in groups.vault_servers -%}
              {{ servers.append(hostname + ' ' +
                hostvars[hostname].ansible_host + ':' + '8200') }}
              {%- endfor -%}
              {{ servers }}
        haproxy_firewall_ports:
          - 8404/tcp
          - 8200/tcp
    - name: keepalived
      vars:
        keepalived_vip: 192.168.3.100
        keepalived_network: >-
          {{ keepalived_vip.split('.')[:-1]|join('.') + '.0' }}
        keepalived_configs:
          global_defs:
            script_user: root root
            enable_script_security:
            notification_email:
              - email@example.com
          vrrp_script:
            - name: chk_haproxy
              script: "'/usr/sbin/pidof haproxy'"
              interval: 5
              weight: 2
          vrrp_instance:
            - name: HAPROXY_LB
              interface: |-
                {%- for key, value in ansible_facts.items() if 
                  value.ipv4.network is defined and 
                  value.ipv4.network == keepalived_network -%}
                {{- key -}}
                {%- endfor -%}
              state: >-
                {{- 'MASTER' if groups.haproxy_servers|first == 
                inventory_hostname else 'BACKUP' -}}
              priority: >-
                {%- for hostname in groups.haproxy_servers|reverse -%}
                  {%- if hostname == inventory_hostname -%}
                    {{- loop.index -}}
                  {%- endif -%}
                {%- endfor -%}
              virtual_router_id: 1
              smtp_alert:
              authentication:
                auth_type: PASS
                auth_pass: mypassword
              unicast_src_ip: >-
                {%- for key, value in ansible_facts.items() if 
                  value.ipv4.network is defined and 
                  value.ipv4.network == keepalived_network -%}
                {{- value.ipv4.address -}}
                {%- endfor -%}
              unicast_peer: >-
                {%- set servers = [] -%}
                {%- for hostname in groups.haproxy_servers if 
                  hostname != inventory_hostname -%}
                  {%- for key, value in hostvars[hostname].ansible_facts.items() if
                    value.ipv4.network is defined and 
                    value.ipv4.network == keepalived_network -%}
                    {{- servers.append(value.ipv4.address) -}}
                  {%- endfor -%}
                {%- endfor -%}
                {{- servers -}}
              virtual_ipaddress:
                - "{{ keepalived_vip }}"
              track_script:
                - chk_haproxy
