- name: save check configuration to file
  copy:
    content: >-
      {% set checkconf = {'check': check} %}
      {% if check.token is not defined or check.token is none %}
      {{ checkconf|combine({'check':{'token': acl_master_token}},
        recursive=True)|to_nice_json(indent=2) }}
      {% else %}
      {{ checkconf|to_nice_json(indent=2) }}
      {% endif %}
    dest: "{{ consul_configd_path }}/{{ (check.name|replace(' ','_') + '_' +
      check.id|default(none, true))|lower }}.json"
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0644
  notify: reload consul