- name: register check
  uri:
    url: >-
      http://127.0.0.1:{{ consul_port }}/v1/agent/check/register
    headers:
      X-Consul-Token: '{{ acl_consul_token }}'
    method: PUT
    body_format: json
    body: '{{ check }}'
  register: register_check_result
