- name: create consul user group
  group:
    name: '{{ consul_group }}'
    state: present

- name: create consul user
  user:
    name: '{{ consul_user }}'
    comment: Consul user
    group: '{{ consul_group }}'
    shell: /bin/false

- name: create consul directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0755
  with_items:
    - "{{ consul_config_path }}"
    - "{{ consul_configd_path }}"
    - "{{ consul_data_path }}"
    - "{{ consul_certs_path }}/certs"
    - "{{ consul_certs_path }}/keys"
    - "{{ consul_log_path }}"
    - "{{ consul_run_path }}"

- set_fact:
    consul_src_base_url: >-
      {{- "https://releases.hashicorp.com/consul/" + consul_version|string -}}

- name: download checksum file
  get_url:
    url: "{{ consul_src_base_url }}/consul_{{ consul_version }}_SHA256SUMS"
    dest: /usr/local/src

- name: read checksum from file
  shell: >-
    /bin/grep consul_{{ consul_version }}_linux_amd64.zip 
    /usr/local/src/consul_{{ consul_version }}_SHA256SUMS | awk '{print $1}'
  register: checksum
  changed_when: false

- name: download consul
  get_url:
    url: "{{ consul_src_base_url }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: /usr/local/src
    checksum: 'sha256:{{ checksum.stdout }}'

- name: install consul
  unarchive:
    src: >-
      /usr/local/src/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    validate_certs: no

- include_tasks: encrypt_keyring.yml

- include_tasks: acl_master_token.yml
  when:
    - consul_config_options.acl.enabled is defined
    - consul_config_options.acl.enabled
    - consul_agent_mode == 'server'

- name: create consul systemd file
  template:
    src: consul_systemd.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart consul

- name: create consul config file
  template:
    src: config.json.j2
    dest: '{{ consul_config_path }}/config.json'
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0640
  notify: restart consul

- name: start consul
  service:
    name: consul
    enabled: yes
    state: started
