- name: install unzip
  package:
    name: unzip
    state: present

- name: add every hosts to /etc/hosts file
  lineinfile: 
    path: /etc/hosts 
    regexp: '^\s*{{ hostvars[item].ansible_host|replace(''.'',''\.'') }}\s+{{ hostvars[item].inventory_hostname|replace(''.'',''\.'') }}'
    line: >-
      {{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname}}
    state: present
    create: yes
  with_items: '{{ groups[consul_servers_group_name] }}'
  when: consul_agent_mode == 'server'

- name: remove loopback entry from /etc/hosts file
  lineinfile: 
    path: /etc/hosts 
    regexp: '^127\.0\.0\.1\s+{{ inventory_hostname }}'
    state: absent
