- name: save service configuration to file
  copy:
    content: >-
      {% set serviceconf = {'service': service} %}
      {% if service.token is not defined or service.token is none %}
      {{ serviceconf|combine({'service':{'token': acl_master_token}},
        recursive=True)|to_nice_json(indent=2) }}
      {% else %}
      {{ serviceconf|to_nice_json(indent=2) }}
      {% endif %}
    dest: "{{ consul_configd_path }}/{{ (service.name|replace(' ','_') + '_' +
      service.id|default(none, true))|lower }}.json"
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0644
  notify: reload consul