---
- name: configure timesyncd config file
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart timesyncd

- name: start timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
