---
- name: install chrony
  package:
   name: chrony
   state: present
  when: ansible_pkg_mgr != "atomic_container"

- name: install chrony
  shell: rpm-ostree install chrony --idempotent
  when: ansible_pkg_mgr == "atomic_container"
  register: chrony_install
  changed_when: false
  failed_when:
    - chrony_install.rc != 0
    - "'is already provided' not in chrony_install.stderr"

- name: configure chrony config file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart chronyd

- name: start chronyd
  service:
    name: chronyd
    enabled: yes
    state: started
